name       : libcec
version    : 3.0.1
release    : 1
source     :
    - https://github.com/Pulse-Eight/libcec/archive/libcec-3.0.1.tar.gz : 7e3670c8949a1964d6e5481f56dfff838857da10bdc60b506f6e9b7f117e253e
license    : GPL-2.0
summary    : Pulse-Eight USB-CEC adapter support.
description: |
    This library provides support for the Pulse-Eight USB-CEC adapter.
builddeps  :
    - pkgconfig(libudev)
    - pkgconfig(platform)
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
