name       : libcec
version    : 4.0.2
release    : 4
source     :
    - https://github.com/Pulse-Eight/libcec/archive/libcec-4.0.2.tar.gz : b8b8dd31f3ebdd5472f03ab7d401600ea0d959b1288b9ca24bf457ef60e2ba27
license    : GPL-2.0
component  : desktop.multimedia
summary    : Pulse-Eight USB-CEC adapter support.
description: |
    This library provides support for the Pulse-Eight USB-CEC adapter.
builddeps  :
    - pkgconfig(libudev)
    - pkgconfig(p8-platform)
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
